### ISSUE TITLE
Extension does not seem to work in 1.3.0 of auto1111 webui

### ISSUE THREAD

**Issue by sashasubbbb** [thomasasfk/sd-webui-aspect-ratio-helper#55]
```
Error calling: B:\AIimages\stable-diffusion-webui\extensions\sd-webui-aspect-ratio-helper\scripts\sd_webui_aspect_ratio_helper.py/ui
Traceback (most recent call last):
  File "B:\AIimages\stable-diffusion-webui\modules\scripts.py", line 283, in wrap_call
    res = func(*args, **kwargs)
  File "B:\AIimages\stable-diffusion-webui\extensions\sd-webui-aspect-ratio-helper\aspect_ratio_helper\main.py", line 54, in ui
    component.render()
  File "B:\AIimages\stable-diffusion-webui\extensions\sd-webui-aspect-ratio-helper\aspect_ratio_helper\_components.py", line 66, in render
    gr.Button(
  File "B:\AIimages\stable-diffusion-webui\venv\lib\site-packages\gradio\events.py", line 132, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "B:\AIimages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 267, in set_event_trigger
    "inputs": [block._id for block in inputs],
  File "B:\AIimages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 267, in <listcomp>
    "inputs": [block._id for block in inputs],
AttributeError: 'NoneType' object has no attribute '_id'
```

**Comment by thomasasfk** [comment]
Having a look at this today

**Comment by thomasasfk** [comment]
I can't seem to reproduce this, does this consistently happen for you?

Are your dependencies all up to date?

**Comment by thomasasfk** [comment]
Closing till someone else reports this as an issue
